### ISSUE TITLE
Download links for more documents

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [phishman/RDA1846#6]
Please checkout this link

http://en.pudn.com/Download/item/id/1911693.html

Not all the files displayed on this page seem to be downloadable, but there are 2 files of particular interest

http://read.pudn.com/downloads454/doc/1911693/RDA1846S%20document/RDA1846S%20SQ%20algorithmic%20introduction.pdf

and 

http://read.pudn.com/downloads454/doc/1911693/RDA1846S%20document/RDA1846S_register_table_20111008.xls

Especially the .xml spreadsheet

If these files get removed, I have downloaded both of them, so please reply to this issue if you can't download them

**Comment by phishman** [comment]
Thanks!

________________________________

**Comment by rogerclarkmelbourne** [comment]
No worries

There were 2 files, I didnt manage do download, so I'll put a watch on this repo in case you manage to get all of the files on that site.

BTW. I have a data capture for the setup to receive on a Baofeng UV-82, and it looks very much like the boiler plate settings in the spreadsheet

**Comment by phishman** [comment]
I’m not sure, been a while since I worked with one and can’t remember off top of my head, but I’ll look into it when I get a chance....

On Dec 20, 2018, at 4:29 AM, Roger Clark <notifications@github.com<mailto:notifications@github.com>> wrote:


No worries

There were 2 files, I didnt manage do download, so I'll put a watch on this repo in case you manage to get all of the files on that site.

BTW. I have a data capture for the setup to receive on a Baofeng UV-82, and it looks very much like the boiler plate settings in the spreadsheet

PS. Do you know what register 0x7F does ?
The spreadsheet says "Page 0" when its 0x0000, but I have data catures that set it to 0x0001

Possibly the whole register bank from 0x02 to 0x7E has multiple copies, controlled by register 0x7F

I'll need to do some testing to confirm, but its a pain to communicate via single data wire SPI with the AT1846S I have inside a Baofeng UV-82

**Comment by rogerclarkmelbourne** [comment]
Just one more snippet of information

Register 0x40 is not documented in any of the docs I have, but it seems to be the key to disabling audio filtering to allow audio below 400Hz to not be attenuated

Its definitely a bit pattern register, the normal setting is 0x30 but setting an extra bit so that its 0x31 allows low flat frequency response down nearly to DC

**Comment by pdpav** [comment]
Hello, rogerclarkmelbourne and phishman. Can I obtain file RDA1846S_register_table_20111008.xls, as I need it? Thanks!
